version: '3.9'

services:
  neo4j:
    image: neo4j:5.2
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password

  shell:
    build:
      context: .
      dockerfile: ./docker/shell/Dockerfile
    container_name: shell
    volumes:
      - .:/app:wr
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
